### ISSUE TITLE
strange error on Ubuntu 20.04

### ISSUE THREAD

**Issue by ealcober** [bluppfisk/coinprice-indicator#91]
Hi After running 'install.sh' I tried to execute the program and get this error
```
./run.sh 
pygame 2.1.2 (SDL 2.0.16, Python 3.8.10)
Hello from the pygame community. https://www.pygame.org/contribute.html
/usr/lib/python3/dist-packages/requests/__init__.py:89: RequestsDependencyWarning: urllib3 (1.26.9) or chardet (3.0.4) doesn't match a supported version!
  warnings.warn("urllib3 ({}) or chardet ({}) doesn't match a supported "
Traceback (most recent call last):
  File "/home/ealcober/Programas/coinprice-indicator/lib/python3.8/site-packages/urllib3/connection.py", line 174, in _new_conn
    conn = connection.create_connection(
  File "/home/ealcober/Programas/coinprice-indicator/lib/python3.8/site-packages/urllib3/util/connection.py", line 72, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "/usr/lib/python3.8/socket.py", line 918, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -2] Nombre o servicio desconocido

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ealcober/Programas/coinprice-indicator/lib/python3.8/site-packages/urllib3/connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "/home/ealcober/Programas/coinprice-indicator/lib/python3.8/site-packages/urllib3/connectionpool.py", line 386, in _make_request
    self._validate_conn(conn)
  File "/home/ealcober/Programas/coinprice-indicator/lib/python3.8/site-packages/urllib3/connectionpool.py", line 1040, in _validate_conn
    conn.connect()
  File "/home/ealcober/Programas/coinprice-indicator/lib/python3.8/site-packages/urllib3/connection.py", line 358, in connect
    self.sock = conn = self._new_conn()
  File "/home/ealcober/Programas/coinprice-indicator/lib/python3.8/site-packages/urllib3/connection.py", line 186, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x7f570ae53b20>: Failed to establish a new connection: [Errno -2] Nombre o servicio desconocido

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/home/ealcober/Programas/coinprice-indicator/lib/python3.8/site-packages/urllib3/connectionpool.py", line 785, in urlopen
    retries = retries.increment(
  File "/home/ealcober/Programas/coinprice-indicator/lib/python3.8/site-packages/urllib3/util/retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='www.mxc.com', port=443): Max retries exceeded with url: /open/api/v2/market/symbols (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f570ae53b20>: Failed to establish a new connection: [Errno -2] Nombre o servicio desconocido'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ealcober/Programas/coinprice-indicator/coin/downloader.py", line 47, in execute
    command.response = get(command.url, timeout=command.timeout)
  File "/usr/lib/python3/dist-packages/requests/api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='www.mxc.com', port=443): Max retries exceeded with url: /open/api/v2/market/symbols (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f570ae53b20>: Failed to establish a new connection: [Errno -2] Nombre o servicio desconocido'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./coin/coin.py", line 371, in <module>
    coin = Coin()
  File "./coin/coin.py", line 55, in __init__
    self._load_assets()
  File "./coin/coin.py", line 128, in _load_assets
    exchange.discover_assets(DownloadService(), lambda *args: None)
  File "/home/ealcober/Programas/coinprice-indicator/coin/exchange.py", line 188, in discover_assets
    downloader.execute(command, cls._handle_discovery_result)
  File "/home/ealcober/Programas/coinprice-indicator/coin/downloader.py", line 51, in execute
    response_handler(None)
  File "/home/ealcober/Programas/coinprice-indicator/coin/exchange.py", line 196, in _handle_discovery_result
    logging.debug("Response from {}: {}".format(command.url, command.error))
AttributeError: 'NoneType' object has no attribute 'url'


```

**Comment by bluppfisk** [comment]
Sounds like you don't have requests installed. Activate the environment and install requests with pip3, you may try the --upgrade flag

**Comment by bluppfisk** [comment]
can you activate the environment and do a `pip3 freeze | grep requests`?

**Comment by ealcober** [comment]
Of course. Thanks. Command does not throw any output :/

**Comment by bluppfisk** [comment]
Then I believe it is not installed. Note it must be installed in the virtual environment, not system-wide.

Output should be as below:

```
~/code/coinprice-indicator$ pip freeze | grep requests
requests==2.25.1
requests-kerberos==0.12.0
requests-ntlm==1.1.0
requests-toolbelt==0.9.1
```

**Comment by bluppfisk** [comment]
closing for now

**Comment by ealcober** [comment]
Ok it's installed but it don't works thats all...

**Comment by bluppfisk** [comment]
without any error output I don't think there's anything I can do to help
